clean:
	-rm *.pyc 
	-rm -r __pycache__
	-rm *.txt
	-rm ./stig*/src/*.txt
	-rm ./stig*/src/.pyc
	-rm ./stig*/src/__pycache__
	-rm ./stig*/test/*.txt
	-rm ./stig*/test/*.pyc
update:
	git pull
	git submodule update --recursive --remote
